var I=function(id){return '<span class="tile"><svg viewBox="0 0 24 24" fill="none" stroke="#7FC492" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><use href="#i-'+id+'"/></svg></span>'};
var F=function(t){return '<span class="flag">'+(t||'Confirm')+'</span>'};
var PH=function(t){return '<span class="ph">['+t+']</span>'};
function hero(o){
  return '<section class="phero'+(o.deep?' phero--deep on-dark':'')+'"><div class="wrap"><div class="crumbs">'+o.crumbs.map(function(c,i){return i<o.crumbs.length-1?'<a data-go="'+c[1]+'">'+c[0]+'</a><span>/</span>':'<span>'+c[0]+'</span>'}).join('')+'</div><div><span class="eyebrow">'+o.eyebrow+'</span><h1>'+o.title+'</h1><p class="sub">'+o.sub+'</p>'+(o.btns||'')+'</div><img src="img/'+o.img+'.jpg" alt="'+(o.alt||'')+'"></div></section>';
}
function cta(title,sub,type){
  return '<section class="sec sec--egg"><div class="wrap" style="display:flex;flex-wrap:wrap;gap:24px 48px;align-items:center;justify-content:space-between"><div><h2 style="font-size:clamp(28px,3cqi,38px);color:var(--deep);max-width:24ch">'+title+'</h2><p style="color:var(--muted);margin-top:10px">'+sub+'</p></div><div class="btns" style="margin:0"><a class="btn btn--primary" data-go="contact" data-type="'+(type||'Sales')+'">Request a sample</a><a class="btn btn--outline" data-go="contact" data-type="General">Contact us</a></div></div></section>';
}
function form(title,fields,btn){
  var ctx=title.replace(/<[^>]+>/g,'');
  var f='<form class="form" data-enquiry data-context="'+ctx+'"><h3>'+title+'</h3>';
  f+='<div class="row"><label>Name<input name="name" autocomplete="name" placeholder="Full name"></label><label>Company<input name="company" autocomplete="organization" placeholder="Company" required></label></div>';
  f+='<div class="row"><label>Work email<input type="email" name="email" autocomplete="email" placeholder="name@company.com" required></label><label>Country<input name="country" autocomplete="country-name" placeholder="Country"></label></div>';
  (fields||[]).forEach(function(x){f+=x});
  f+='<label>Message<textarea name="message" required placeholder="Tell us the polymer, process and application"></textarea></label><div><button class="btn btn--primary" type="submit">'+(btn||'Send inquiry')+'</button></div><p class="status" role="status" aria-live="polite" hidden></p></form>';
  return f;
}
var sel=function(label,opts){return '<label>'+label+'<select data-field="'+label+'">'+opts.map(function(o){return '<option>'+o+'</option>'}).join('')+'</select></label>'};

/* ---------- product data ---------- */
var PRODUCTS={
  'p-core':{name:'Ecoshell Core',plat:'Core masterbatches',platId:'core-mb',img:'pellets',icon:'material',
    desc:'General-purpose bio-calcium masterbatch for PP and HDPE. The starting point for most qualification trials.',
    apps:['Totes and crates','Caps and closures','Jars and containers','Household goods','Horticulture pots']},
  'p-flow':{name:'Ecoshell Flow',plat:'Core masterbatches',platId:'core-mb',img:'pellets',icon:'material',
    desc:'Masterbatch tuned for flow in thin-wall and fast-cycle injection moulding.',
    apps:['Thin-wall containers','Lids','Closures','Cosmetic components']},
  'p-expand':{name:'Ecoshell Expand',plat:'Core masterbatches',platId:'core-mb',img:'tray',icon:'material',
    desc:'Masterbatch for extrusion, sheet and film where melt strength and surface finish matter.',
    apps:['Sheet','Profiles','Blown and cast film','Thermoformed trays']},
  'p-mold':{name:'Ecoshell Mold',plat:'Core masterbatches',platId:'core-mb',img:'crate',icon:'material',
    desc:'Masterbatch for injection and blow moulding of durable and returnable parts.',
    apps:['Returnable transit packaging','HDPE bottles','Pails','Hard goods']},
  'p-complete':{name:'Ecoshell Complete',plat:'Core masterbatches',platId:'core-mb',img:'process',icon:'material',
    desc:'Ready-to-run compound. No let-down or blending needed on your line.',
    apps:['Converters without dosing equipment','Pilot runs','Short production runs']},
  'p-bioflex':{name:'Ecoshell Bioflex',plat:'Compostable platform',platId:'compostable',img:'tray',icon:'leaf',
    desc:'Compostable flexible grade for films and bags.',
    apps:['Produce and carrier bags','Liners','Mailers','Agricultural film']},
  'p-bioform':{name:'Ecoshell Bioform',plat:'Compostable platform',platId:'compostable',img:'process',icon:'leaf',
    desc:'Compostable grade for thermoformed packaging.',
    apps:['Trays','Clamshells','Cups and lids']},
  'p-bioshape':{name:'Ecoshell Bioshape',plat:'Compostable platform',platId:'compostable',img:'pellets',icon:'leaf',
    desc:'Compostable grade for injection-moulded items.',
    apps:['Cutlery','Plant pots','Single-use service items']},
  'p-shield':{name:'Ecoshell Shield',plat:'Antibacterial platform',platId:'antibacterial',img:'crate',icon:'shield',
    desc:'Bio-calcium masterbatch designed to protect the plastic article itself from bacterial growth.',
    apps:['Food-service trays (article protection)','Shower and bath products','Storage containers','Handles and touch surfaces']}
};
var CUSTOM={
  'p-custom':{name:'Custom masterbatch',plat:'Core masterbatches',platId:'core-mb',icon:'custom',img:'pellets',
    desc:'A grade developed around your resin, process and part. We adjust loading, carrier and additives to fit your window.',
    caps:['Custom loading levels','Colour and additive packages','Carrier resin matching','Trial and scale-up support']},
  'p-abcustom':{name:'Custom antibacterial',plat:'Antibacterial platform',platId:'antibacterial',icon:'custom',img:'crate',
    desc:'Antibacterial grades formulated for a specific polymer, process and end use.',
    caps:['Polymer and process matching','Efficacy testing plans','Regulatory pathway support','Pilot and scale-up']}
};

function productPage(id){
  var p=PRODUCTS[id];
  var ab=p.platId==='antibacterial', comp=p.platId==='compostable';
  var h=hero({crumbs:[['Home','home'],['Products & services','products'],[p.plat,p.platId],[p.name.replace('Ecoshell ','')]],eyebrow:p.plat,title:p.name,sub:p.desc+' '+F('Draft copy'),img:p.img,
    btns:'<div class="btns"><a class="btn btn--primary" data-anchor="inquiry">Make an inquiry</a><a class="btn btn--outline" data-anchor="downloads">TDS / SDS download</a></div>'});
  h+='<div class="ptabs"><div class="wrap"><a data-anchor="desc">Description</a><a data-anchor="apps">Applications</a><a data-anchor="tech">Technical information</a><a data-anchor="certs">Certifications</a><a data-anchor="inquiry">Inquiry</a></div></div>';
  h+='<section class="sec" id="desc"><div class="wrap split"><div><span class="eyebrow">Description</span><h2 style="font-size:clamp(28px,3cqi,38px);color:var(--deep);margin-top:10px">What it is and where it fits</h2><hr class="rule"></div><div class="prose"><p class="lead">'+p.desc+'</p><p>'+PH('Two or three sentences on what makes this grade different: the problem it solves, the processing window and the typical let-down ratio.')+'</p>'+(ab?'<div class="note-box" style="margin-top:18px">Public health claims (for example, "kills germs") need EPA registration. Until it is granted, copy is limited to protecting the article itself.'+F('Regulatory review')+'</div>':'')+(comp?'<div class="note-box" style="margin-top:18px">Compostability claims must name the standard, the certifier and the conditions (industrial or home).'+F('Certificate needed')+'</div>':'')+'</div></div></section>';
  h+='<section class="sec sec--mist" id="apps"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">Applications</span><h2>Where '+p.name.replace('Ecoshell ','')+' is used</h2></div></div><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(min(200px,100%),1fr))">'+p.apps.map(function(a){return '<div class="card"><h3 style="font-size:19px">'+a+'</h3><p>'+PH('One-line use case')+'</p></div>'}).join('')+'</div></div></section>';
  h+='<section class="sec" id="tech"><div class="wrap split"><div><span class="eyebrow">Technical information</span><h2 style="font-size:clamp(28px,3cqi,38px);color:var(--deep);margin-top:10px">Typical properties</h2><p style="color:var(--muted);margin-top:14px">Values from the technical data sheet. Request the full TDS for test methods.</p></div><div class="table-wrap"><table><thead><tr><th>Property</th><th>Value</th><th>Method</th></tr></thead><tbody>'+
    [['Carrier resin',comp?'[Compostable carrier]':'PP / HDPE'],['Bio-calcium content','[%]'],['Recommended let-down','[% range]'],['Melt flow index','[g/10 min]'],['Density','[g/cm³]'],['Moisture','[%]'],['Processes',comp?'[Processes]':'Injection, extrusion, blow moulding, thermoforming'],['Pack size','[25 kg bags / 1 t bulk]']].map(function(r){return '<tr><th>'+r[0]+'</th><td>'+(r[1].charAt(0)==='['?'<span class="ph">'+r[1]+'</span>':r[1])+'</td><td><span class="ph">[ASTM / ISO]</span></td></tr>'}).join('')+'</tbody></table></div></div></section>';
  h+='<section class="sec sec--mist" id="certs"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">Certifications</span><h2>Certifications and compliance</h2></div><p>Show only credentials that apply to this exact grade, with the scope and authorised artwork.</p></div><div class="grid g4">'+
    (comp?[['C','Compostability','[Standard and certifier]'],['B','Bio-based content','[Certificate]']]:ab?[['E','EPA registration','Pending'],['T','Efficacy testing','[Lab and method]']]:[['P','Patent','[Patent number]'],['R','Recyclability','[Test basis]']]).concat([['S','Safety data','SDS available'],['Q','Quality','[ISO 9001 or equivalent]']]).map(function(b){return '<div class="badge"><i>'+b[0]+'</i><b>'+b[1]+'</b><small>'+b[2]+'</small></div>'}).join('')+'</div></div></section>';
  h+='<section class="sec" id="inquiry"><div class="wrap gate"><div>'+form('Inquire about '+p.name,['<div class="row">'+sel('Polymer',['PP','HDPE','Other'])+sel('Process',['Injection moulding','Extrusion','Blow moulding','Thermoforming','Other'])+'</div>'],'Send inquiry')+'</div><div class="side" id="downloads"><span class="eyebrow">Downloads</span><a class="dl"><i>PDF</i><div><b>Technical data sheet (TDS)</b><small>'+p.name+' · [version]</small></div></a><a class="dl"><i>PDF</i><div><b>Safety data sheet (SDS)</b><small>'+p.name+' · [version]</small></div></a><a class="dl"><i>PDF</i><div><b>Processing guide</b><small>Let-down, drying, settings</small></div></a><p style="font-size:14px;color:var(--stone)">Downloads ask for a work email first.'+F('Your choice')+'</p></div></div></section>';
  return h;
}
function customPage(id){
  var p=CUSTOM[id];
  var h=hero({crumbs:[['Home','home'],['Products & services','products'],[p.plat,p.platId],['Custom']],eyebrow:p.plat,title:p.name,sub:p.desc,img:p.img,btns:'<div class="btns"><a class="btn btn--primary" data-anchor="inquiry">Start a custom project</a></div>'});
  h+='<section class="sec"><div class="wrap split"><div><span class="eyebrow">Description</span><h2 style="font-size:clamp(28px,3cqi,38px);color:var(--deep);margin-top:10px">Built around your part</h2><hr class="rule"></div><div class="prose"><p class="lead">'+p.desc+'</p><p>'+PH('How a custom project runs, typical timeline and minimum volumes.')+'</p></div></div></section>';
  h+='<section class="sec sec--mist"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">Capabilities</span><h2>What we can tune</h2></div></div><div class="grid g4">'+p.caps.map(function(c){return '<div class="card">'+I(p.icon)+'<h3 style="font-size:19px">'+c+'</h3><p>'+PH('Short detail')+'</p></div>'}).join('')+'</div></div></section>';
  h+='<section class="sec" id="inquiry"><div class="wrap gate"><div>'+form('Start a custom project',['<div class="row">'+sel('Polymer',['PP','HDPE','Other'])+sel('Annual volume',['Under 10 t','10 to 100 t','100 to 1,000 t','Over 1,000 t'])+'</div>'],'Send inquiry')+'</div><div class="side"><div class="note-box">We reply with a short questionnaire on your resin, process settings and part requirements, then propose a trial plan.</div></div></div></section>';
  return h;
}
function platformLinks(ids){
  return '<div class="grid g3">'+ids.map(function(id){var p=PRODUCTS[id]||CUSTOM[id];return '<a class="card" data-go="'+id+'">'+I(p.icon)+'<h3>'+p.name.replace('Ecoshell ','')+'</h3><p>'+p.desc+'</p><span class="arrow">View product</span></a>'}).join('')+'</div>';
}

/* ---------- pages ---------- */
var P={};
P.home={t:'Home',url:'',r:function(){
  var SL=[['hero','Eggshell-derived materials','Less plastic, made from eggshell','Ecoshell turns eggshell waste into bio-calcium materials that cut the plastic in your products and run on the equipment you already have.'+F('Tagline'),'<a class="btn btn--lime" data-go="contact" data-type="Sales">Request a sample</a><a class="btn btn--outline" style="color:#fff" data-go="products">Explore products</a>',true,'hero'],
    ['pellets','Core masterbatches','Plastic reduction at the hopper','Bio-calcium masterbatches for PP and HDPE. Add at the hopper and keep your process settings.','<a class="btn btn--lime" data-go="core-mb">Explore Core</a>'],
    ['process','Sustainability','Meet EPR targets with data','Per-SKU reduction data you can report to regulators, retailers and your own board.','<a class="btn btn--lime" data-go="sustainability" data-anchor="epr">See EPR solutions</a>'],
    ['crate','Antibacterial platform','Materials that protect the article','Shield grades are designed to keep plastic items protected from bacterial growth.'+F('EPA'),'<a class="btn btn--lime" data-go="antibacterial">Explore Shield</a>']];
  var h='<section class="hhero"><div class="car" id="car">'+SL.map(function(x,i){return '<div class="slide" data-slide="'+i+'"'+(i?' hidden':'')+'>'+(x[6]?'<video src="video/'+x[6]+'.mp4" poster="img/'+x[0]+'.jpg" autoplay muted loop playsinline aria-hidden="true"></video>':'<img src="img/'+x[0]+'.jpg" alt="">')+'<div class="wrap"><div class="txt"><span class="eyebrow">'+x[1]+'</span><h2>'+x[2]+'</h2><p>'+x[3]+'</p><div class="btns" style="margin-top:6px">'+x[4]+'</div></div></div>'+(x[5]?'<div class="readout"><b>Ecoshell bio calcium</b><div><span>Composition</span><span>CaCO<sub>3</sub> [≥ XX]%</span></div><div><span>Particle size D50</span><span>[X.X] µm</span></div><div><span>Source</span><span>Post-industrial eggshell</span></div><div><span>Carrier</span><span>PP · HDPE</span></div></div>':'')+'</div>'}).join('')+'</div><div class="car__dots" id="dots">'+SL.map(function(x,i){return '<button aria-label="Slide '+(i+1)+'" data-dot="'+i+'"'+(i?'':' aria-current="true"')+'></button>'}).join('')+'</div>';
  h+='<div class="benefits"><div class="wrap"><div class="col"><h3>For your business</h3><ul><li>Reduce plastic content without new tooling'+F('Proof')+'</li><li>Meet EPR and plastic-reduction targets with documented data</li><li>Stable cost against virgin resin'+F('Proof')+'</li></ul></div><div class="col"><h3>For the environment</h3><ul><li>Puts a food-waste stream to work instead of landfill</li><li>Less fossil-based polymer per part'+F('LCA')+'</li><li>Stays in existing PP and PE recycling streams'+F('Proof')+'</li></ul></div></div></div></section>';
  h+='<section class="sec"><div class="wrap split split--center"><div><span class="eyebrow">What is Ecoshell</span><h2 style="font-size:clamp(30px,3.4cqi,42px);color:var(--deep);margin-top:10px">Bio calcium from the world\'s eggshells</h2><hr class="rule"><p class="formula" style="margin-top:36px">CaCO<sub>3</sub></p><p style="font:400 13px/1.5 var(--f-display);color:var(--stone);letter-spacing:.06em;margin-top:8px">Calcium carbonate, about 95% of eggshell by mass'+F('Verify')+'</p></div><div class="prose"><p class="lead">Ecoshell develops eggshell-derived materials for plastic reduction and supports customers through masterbatches, finished products and manufacturing services.</p><p>We clean, mill and treat eggshell into a fine bio-calcium powder, then compound it into masterbatches that replace part of the polymer in a plastic product.</p><p style="margin-top:20px"><a class="arrow" data-go="products">How it is made and used</a></p></div></div></section>';
  var ind=[['Consumer packaging','Jars, bottles, caps and closures'],['Cosmetics and personal care','Refillable and rigid packs'],['Horticulture','Pots, trays and nursery goods'],['Logistics','Totes, crates and pallets'],['Food service','Cutlery, trays and containers'],['Household and bath','Shower liners and storage'],['Retail and e-commerce','Bags, mailers and films'],['Government and public works','Procurement to existing specs']];
  h+='<section class="sec sec--mist"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">Industries we serve</span><h2>Where Ecoshell is used</h2></div><p>Anywhere PP or HDPE parts are moulded, extruded or formed.</p></div><div class="ind">'+ind.map(function(x){return '<div><h3>'+x[0]+'</h3><p>'+x[1]+'</p></div>'}).join('')+'</div></div></section>';
  h+='<section class="sec"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">Products</span><h2>Find the right material</h2></div><a class="arrow" data-go="products">All products and services</a></div><div class="grid g4">'+
    '<a class="card card--img" data-go="core-mb"><img src="img/pellets.jpg" alt=""><div class="body"><span class="tag">Platform</span><h3>Core masterbatches</h3><p>Plastic reduction for PP and HDPE on existing lines.</p><span class="arrow">Explore</span></div></a>'+
    '<a class="card card--img" data-go="antibacterial"><img src="img/crate.jpg" alt=""><div class="body"><span class="tag">Platform</span><h3>Antibacterial</h3><p>Bio-calcium grades that protect the article itself.</p><span class="arrow">Explore</span></div></a>'+
    '<a class="card card--img" data-go="compostable"><img src="img/tray.jpg" alt=""><div class="body"><span class="tag">Platform</span><h3>Compostable</h3><p>Grades for films, thermoforms and moulded items.</p><span class="arrow">Explore</span></div></a>'+
    '<a class="card card--img" data-go="sustainability" data-anchor="epr"><img src="img/process.jpg" alt=""><div class="body"><span class="tag">Solutions</span><h3>EPR solutions</h3><p>Use Ecoshell to lower fees and meet reduction targets.</p><span class="arrow">See examples</span></div></a></div></div></section>';
  var logos=[];for(var i=1;i<=10;i++)logos.push('<span>Client logo '+i+'</span>');
  h+='<section class="sec--egg" style="padding-block:56px 64px"><div class="wrap"><div class="sec-head" style="margin-bottom:24px"><div><span class="eyebrow">Who we work with</span><h2 style="font-size:clamp(26px,2.6cqi,32px)">Trusted by converters and brands</h2></div><p style="font-size:14.5px">Logos appear only with each client\'s written permission.'+F('Permission')+'</p></div></div><div class="marquee"><div class="marquee__track">'+logos.join('')+logos.join('')+'</div></div></section>';
  h+='<section class="sec"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">Badges and certificates</span><h2>Credentials</h2></div><p>Each badge links to the certificate, its scope and the grades it covers.</p></div><div class="grid g4"><div class="badge"><i>PW</i><b>PREVENT Waste Alliance</b><small>Member</small></div><div class="badge"><i>P</i><b>Patented technology</b><small>[Patent number]'+F()+'</small></div><div class="badge"><i>C</i><b>[Compostability certificate]</b><small>[Certifier]'+F()+'</small></div><div class="badge"><i>R</i><b>[Recyclability / LCA verification]</b><small>[Verifier]'+F()+'</small></div></div></div></section>';
  return h+cta('Tell us the polymer, process and application','We will come back with a sample plan and a clear view of fit.');
}};
P.sustainability={t:'Sustainability',url:'sustainability',sec:'sustainability',r:function(){
  var h=hero({crumbs:[['Home','home'],['Sustainability']],eyebrow:'Sustainability',title:'Plastic reduction you can measure',sub:'Our stance is simple: every environmental claim we make sits next to the test or study that supports it.',img:'process',deep:true});
  h+='<section class="sec"><div class="wrap split"><div><span class="eyebrow">Our stance and approach</span><h2 style="font-size:clamp(28px,3cqi,38px);color:var(--deep);margin-top:10px">Practical, measured, specific</h2><hr class="rule"></div><div class="prose"><p class="lead">We reduce the fossil plastic in everyday products by replacing part of it with a mineral that would otherwise be waste.</p><p>We do not claim products are "zero impact" or "100% sustainable". We publish the baseline, the percentage by mass and the tested formulation for each grade, and we keep LCA results tied to their study boundary and date.</p></div></div></section>';
  h+='<section class="sec sec--deep on-dark" id="lca"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">Plastic reduction and LCA</span><h2>The numbers</h2></div><p>Figures shown are placeholders until the LCA and test reports are final.</p></div><div class="grid g4"><div class="stat"><b>[XX]%</b><span>Polymer replaced by mass, typical grade'+F('Test data')+'</span></div><div class="stat"><b>[X.X] kg</b><span>CO₂e avoided per kg of masterbatch'+F('LCA')+'</span></div><div class="stat"><b>[XX] t</b><span>Eggshell diverted from landfill to date'+F('Data')+'</span></div><div class="stat"><b>[Date]</b><span>LCA study date, boundary and reviewer'+F('LCA')+'</span></div></div><p style="margin-top:32px"><a class="arrow" data-go="resources">Download the LCA summary</a></p></div></section>';
  h+='<section class="sec" id="targets"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">How to use Ecoshell to meet your targets</span><h2>From target to production</h2></div></div><div class="steps"><div><h3>Set the target</h3><p>Name the requirement: a reduction goal, an EPR fee tier or a customer specification.</p></div><div><h3>Choose the grade</h3><p>We match a masterbatch to your polymer, process and part.</p></div><div><h3>Trial and test</h3><p>Run a pilot on your line and confirm performance and reduction.</p></div><div><h3>Document and report</h3><p>Get per-SKU data for your sustainability and EPR reporting.</p></div></div></div></section>';
  h+='<section class="sec sec--mist" id="epr"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">EPR solutions</span><h2>Example solutions by requirement</h2></div><p>Illustrative examples. Programme rules vary by state and country and change often.'+F('Legal review')+'</p></div><div class="table-wrap"><table><thead><tr><th>Requirement</th><th>What it asks</th><th>How Ecoshell can help</th></tr></thead><tbody>'+
    '<tr><th>Source reduction targets<br><small style="font-weight:400;color:var(--stone)">e.g. California SB 54</small></th><td>Cut plastic packaging by weight over time</td><td>Lower polymer content per part, with mass data per SKU</td></tr>'+
    '<tr><th>Eco-modulated EPR fees<br><small style="font-weight:400;color:var(--stone)">e.g. Oregon, Colorado</small></th><td>Fees scale with material, weight and recyclability</td><td>Less plastic by weight; stays in the existing PP / PE stream'+F('Proof')+'</td></tr>'+
    '<tr><th>Plastic packaging taxes<br><small style="font-weight:400;color:var(--stone)">e.g. UK, Spain</small></th><td>Tax per tonne of plastic packaging</td><td>Fewer taxable tonnes of virgin plastic'+F('Tax advice')+'</td></tr>'+
    '<tr><th>EU packaging regulation<br><small style="font-weight:400;color:var(--stone)">PPWR</small></th><td>Minimisation, recyclability and reporting duties</td><td>Material reduction with documentation for your file</td></tr>'+
    '<tr><th>Customer or retailer specs</th><td>Corporate plastic-reduction commitments</td><td>Per-SKU reduction data you can report and defend</td></tr></tbody></table></div></div></section>';
  return h+cta('Need help mapping a requirement?','Tell us the programme and the SKUs. We will suggest a grade and the data you need.','General');
}};
P.products={t:'Products & services',url:'products',sec:'products',r:function(){
  var h=hero({crumbs:[['Home','home'],['Products & services']],eyebrow:'Products & services',title:'One material, many routes to market',sub:'Start with a masterbatch, choose a finished Ecoshell product, or let us make your product for you.',img:'pellets'});
  h+='<section class="sec"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">Our material</span><h2>How it is made and how it is used</h2></div></div><div class="steps"><div><h3>Collect</h3><p>Eggshell is recovered from egg-breaking plants and food processors.</p></div><div><h3>Clean and mill</h3><p>Shells are cleaned, membranes removed and milled into fine bio calcium.</p></div><div><h3>Compound</h3><p>The powder is compounded into masterbatch with a carrier resin.</p></div><div><h3>Mould or form</h3><p>You add it at the hopper and run your normal process.</p></div></div><p style="margin-top:24px;font-size:14.5px;color:var(--stone)">Process steps to confirm with operations.'+F()+'</p></div></section>';
  h+='<section class="sec sec--mist"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">Explore</span><h2>Platforms, products and services</h2></div></div><div class="grid g3">'+
    [['core-mb','material','Core masterbatches','Plastic reduction for PP and HDPE. Core, Flow, Expand, Mold, Complete and Custom.'],
     ['compostable','leaf','Compostable platform','Bioflex, Bioform and Bioshape for films, thermoforms and moulded items.'],
     ['antibacterial','shield','Antibacterial platform','Shield and custom grades that protect the plastic article.'],
     ['ecoproducts','packaging','Ecoshell products','Shower liners, bags and films, and cutlery made with Ecoshell.'],
     ['oem','manufacturing','OEM services','Design, tooling, production and logistics under your brand.'],
     ['p-custom','custom','Custom development','A grade developed around your resin, process and part.']].map(function(c){return '<a class="card" data-go="'+c[0]+'">'+I(c[1])+'<h3>'+c[2]+'</h3><p>'+c[3]+'</p><span class="arrow">Explore</span></a>'}).join('')+'</div></div></section>';
  return h+cta('Not sure where to start?','Tell us the part and we will point you to the right platform.');
}};
P['core-mb']={t:'Core masterbatches',url:'products/core-masterbatches',sec:'products',r:function(){
  var h=hero({crumbs:[['Home','home'],['Products & services','products'],['Core masterbatches']],eyebrow:'Platform',title:'Core masterbatches',sub:'Bio-calcium masterbatches that replace part of the polymer in PP and HDPE products, on your existing line.',img:'pellets',btns:'<div class="btns"><a class="btn btn--primary" data-go="contact" data-type="Sales">Request a sample</a><a class="btn btn--outline" data-anchor="range">See the range</a></div>'});
  h+='<section class="sec"><div class="wrap split"><div><span class="eyebrow">Advantages and how to use</span><h2 style="font-size:clamp(28px,3cqi,38px);color:var(--deep);margin-top:10px">Add at the hopper, run as normal</h2><hr class="rule"></div><div><dl class="list"><div><dt>Drop-in</dt><dd>Dose with standard gravimetric or volumetric feeders'+F('Proof')+'</dd></div><div><dt>Less plastic</dt><dd>Replace '+PH('XX')+'% of polymer by mass'+F('Test data')+'</dd></div><div><dt>Stiffness</dt><dd>Higher stiffness and heat deflection for durable parts'+F('Test data')+'</dd></div><div><dt>Recyclable</dt><dd>Stays in existing PP and PE streams'+F('Proof')+'</dd></div><div><dt>How to use</dt><dd>Let-down '+PH('X–XX')+'%, dry if required, keep your process settings</dd></div></dl></div></div></section>';
  h+='<section class="sec sec--mist"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">Industries and applications</span><h2>Where Core masterbatches fit</h2></div></div><div class="chips">'+['Totes and crates','Caps and closures','Jars','HDPE bottles','Thin-wall containers','Sheet and thermoforms','Horticulture pots','Household goods','Returnable transit packaging','Hard goods'].map(function(x){return '<span>'+x+'</span>'}).join('')+'</div></div></section>';
  h+='<section class="sec"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">Our process</span><h2>Evaluation, pilot, testing</h2></div><p>Every new account follows the same path from first sample to production.</p></div><div class="steps"><div><h3>Evaluation</h3><p>We review your resin, process, part and targets, and recommend a grade.</p></div><div><h3>Pilot</h3><p>A trial run on your line with our technical team on hand.</p></div><div><h3>Testing</h3><p>Mechanical, processing and reduction tests against your baseline.</p></div><div><h3>Production</h3><p>Scale-up with supply terms and documentation.</p></div></div></div></section>';
  h+='<section class="sec sec--egg"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">How we differ from limestone</span><h2>Ecoshell vs. limestone calcium carbonate</h2></div><p>Both are calcium carbonate. Differences below need test data before publishing.'+F('Test data')+'</p></div><div class="table-wrap"><table class="compare"><thead><tr><th></th><th>Ecoshell bio calcium</th><th>Mined limestone (GCC)</th></tr></thead><tbody><tr><th>Source</th><td>Food-waste eggshell</td><td>Quarried rock</td></tr><tr><th>Mining impact</th><td>None, uses an existing waste stream</td><td>Quarrying and blasting</td></tr><tr><th>Particle structure</th><td>'+PH('Porous, organic-matrix structure')+'</td><td>Dense crystalline particles</td></tr><tr><th>Carbon footprint</th><td>'+PH('LCA result')+'</td><td>'+PH('Literature value')+'</td></tr><tr><th>Story for brands</th><td>Circular, upcycled food waste</td><td>Mineral filler</td></tr></tbody></table></div></div></section>';
  h+='<section class="sec" id="range"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">The range</span><h2>Core masterbatch products</h2></div></div>'+platformLinks(['p-core','p-flow','p-expand','p-mold','p-complete','p-custom'])+'</div></section>';
  return h+cta('Ready to trial Core on your line?','Tell us the polymer, process and part.');
}};
P.compostable={t:'Compostable platform',url:'products/compostable',sec:'products',r:function(){
  var h=hero({crumbs:[['Home','home'],['Products & services','products'],['Compostable platform']],eyebrow:'Platform',title:'Compostable platform',sub:'Eggshell bio calcium in compostable grades for films, thermoforms and moulded items.',img:'tray'});
  h+='<section class="sec"><div class="wrap split"><div><span class="eyebrow">Advantages</span><h2 style="font-size:clamp(28px,3cqi,38px);color:var(--deep);margin-top:10px">Why add eggshell to compostables</h2><hr class="rule"></div><div><dl class="list"><div><dt>Cost</dt><dd>'+PH('Lower cost than unfilled compostable resin')+F('Proof')+'</dd></div><div><dt>Stiffness</dt><dd>'+PH('Improved rigidity and heat resistance')+F('Test data')+'</dd></div><div><dt>End of life</dt><dd>'+PH('Certified to [standard] for [industrial/home] composting')+F('Certificate')+'</dd></div></dl><div class="note-box" style="margin-top:20px">The FTC Green Guides require compostability claims to be qualified when facilities are not available to most consumers.</div></div></div></section>';
  h+='<section class="sec sec--mist"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">Line of products and applications</span><h2>The range</h2></div></div>'+platformLinks(['p-bioflex','p-bioform','p-bioshape'])+'</div></section>';
  h+='<section class="sec"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">Certifications</span><h2>Compostability credentials</h2></div></div><div class="grid g4"><div class="badge"><i>C</i><b>[BPI / TÜV OK compost]</b><small>[Scope]'+F()+'</small></div><div class="badge"><i>EN</i><b>[EN 13432 / ASTM D6400]</b><small>[Grades covered]'+F()+'</small></div><div class="badge"><i>H</i><b>[Home compost]</b><small>[If applicable]'+F()+'</small></div><div class="badge"><i>B</i><b>[Bio-based content]</b><small>[Certificate]'+F()+'</small></div></div></div></section>';
  return h+cta('Exploring compostable formats?','Tell us the item, the target standard and the volume.');
}};
P.antibacterial={t:'Antibacterial platform',url:'products/antibacterial',sec:'products',r:function(){
  var h=hero({crumbs:[['Home','home'],['Products & services','products'],['Antibacterial platform']],eyebrow:'Platform',title:'Antibacterial platform',sub:'Bio-calcium grades designed to protect plastic articles from bacterial growth.',img:'crate'});
  h+='<section class="sec"><div class="wrap split"><div><span class="eyebrow">Advantages and mechanism</span><h2 style="font-size:clamp(28px,3cqi,38px);color:var(--deep);margin-top:10px">How it works</h2><hr class="rule"></div><div class="prose"><p class="lead">'+PH('Plain-language explanation of the mechanism, e.g. how treated eggshell calcium inhibits bacterial growth on the article surface.')+'</p><dl class="list" style="margin-top:20px"><div><dt>Built in</dt><dd>Part of the material, not a coating that wears off'+F('Proof')+'</dd></div><div><dt>Bio-based</dt><dd>Derived from eggshell rather than silver or synthetic biocides'+F('Confirm')+'</dd></div><div><dt>Tested</dt><dd>'+PH('ISO 22196 results vs. untreated control')+'</dd></div></dl><div class="note-box" style="margin-top:20px">Until EPA registration is granted, copy is limited to protecting the article itself (treated-article wording). No claims about protecting people from germs.'+F('Regulatory review')+'</div></div></div></section>';
  h+='<section class="sec sec--mist"><div class="wrap grid g2" style="gap:32px"><div><span class="eyebrow">Applications today</span><h2 style="font-size:clamp(26px,2.6cqi,32px);color:var(--deep);margin:10px 0 20px">Article protection</h2><div class="chips">'+['Storage containers','Shower and bath products','Handles','Trays','Bins'].map(function(x){return '<span>'+x+'</span>'}).join('')+'</div></div><div><span class="eyebrow">Once the EPA certificate is received</span><h2 style="font-size:clamp(26px,2.6cqi,32px);color:var(--deep);margin:10px 0 20px">Public health applications'+F('Pending EPA')+'</h2><div class="chips">'+['Healthcare surfaces','Food-service equipment','Public transit touch points','Schools'].map(function(x){return '<span style="border-style:dashed;color:var(--stone)">'+x+'</span>'}).join('')+'</div></div></div></section>';
  h+='<section class="sec"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">The range</span><h2>Antibacterial products</h2></div></div><div class="grid g2">'+['p-shield','p-abcustom'].map(function(id){var p=PRODUCTS[id]||CUSTOM[id];return '<a class="card" data-go="'+id+'">'+I(p.icon)+'<h3>'+p.name.replace('Ecoshell ','')+'</h3><p>'+p.desc+'</p><span class="arrow">View product</span></a>'}).join('')+'</div></div></section>';
  return h+cta('Have an application in mind?','Tell us the article and the environment it is used in.');
}};
Object.keys(PRODUCTS).forEach(function(id){P[id]={t:PRODUCTS[id].name.replace('Ecoshell ',''),url:'products/'+id.slice(2),sec:'products',parent:PRODUCTS[id].platId,r:function(){return productPage(id)}}});
Object.keys(CUSTOM).forEach(function(id){P[id]={t:'Custom ('+(id==='p-custom'?'Core':'Antibacterial')+')',url:'products/'+id.slice(2),sec:'products',parent:CUSTOM[id].platId,r:function(){return customPage(id)}}});
P.oem={t:'OEM services',url:'products/oem',sec:'products',r:function(){
  var h=hero({crumbs:[['Home','home'],['Products & services','products'],['OEM services']],eyebrow:'Services',title:'OEM and ODM services',sub:'A finished product under your brand, made with Ecoshell. Design, tooling, production, assembly and logistics in one place.',img:'crate',btns:'<div class="btns"><a class="btn btn--primary" data-anchor="inquiry">Start a project</a></div>'});
  h+='<section class="sec"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">Services</span><h2>What we do</h2></div></div><div class="grid g4">'+[['Design','Part design and material selection'],['Tooling','New moulds or use of your existing tools'],['Production','Moulding, assembly and finishing'],['Logistics','Packing and shipping to your sites']].map(function(c){return '<div class="card">'+I('manufacturing')+'<h3>'+c[0]+'</h3><p>'+c[1]+'</p></div>'}).join('')+'</div></div></section>';
  h+='<section class="sec sec--mist"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">Process</span><h2>From brief to delivery</h2></div></div><div class="steps"><div><h3>Brief</h3><p>Share the product, volumes and target cost.</p></div><div><h3>Prototype</h3><p>Samples in Ecoshell material for approval.</p></div><div><h3>Production</h3><p>Manufacture with our partner network.</p></div><div><h3>Delivery</h3><p>Packed, labelled and shipped.</p></div></div></div></section>';
  h+='<section class="sec"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">Examples</span><h2>Recent projects</h2></div><p>Project names and images to be supplied.'+F('Examples')+'</p></div><div class="grid g3">'+[['crate','Reusable crate','[Client / sector]'],['tray','Thermoformed tray','[Client / sector]'],['process','Cosmetic jar','[Client / sector]']].map(function(x){return '<div class="card card--img"><img src="img/'+x[0]+'.jpg" alt=""><div class="body"><span class="tag">'+x[2]+'</span><h3>'+x[1]+'</h3><p>'+PH('One-line result')+'</p></div></div>'}).join('')+'</div></div></section>';
  h+='<section class="sec sec--egg" id="inquiry"><div class="wrap gate"><div>'+form('OEM inquiry',['<div class="row">'+sel('Product type',['Packaging','Household','Industrial','Other'])+sel('Annual volume',['Under 10k units','10k to 100k','100k to 1M','Over 1M'])+'</div>'],'Send inquiry')+'</div><div class="side"><div class="note-box">We reply with a short brief template and a call to scope the project.</div></div></div></section>';
  return h;
}};
P.ecoproducts={t:'Ecoshell products',url:'products/ecoshell-products',sec:'products',r:function(){
  var h=hero({crumbs:[['Home','home'],['Products & services','products'],['Ecoshell products']],eyebrow:'Ecoshell products',title:'Products made with Ecoshell',sub:'Our own finished goods, available in bulk, at retail, or as a starting point for an OEM partnership.',img:'process'});
  h+='<section class="sec"><div class="wrap split"><div><span class="eyebrow">Capabilities and projects</span><h2 style="font-size:clamp(28px,3cqi,38px);color:var(--deep);margin-top:10px">Proof in everyday products</h2><hr class="rule"></div><div class="prose"><p class="lead">We make finished products to show what Ecoshell material can do, and to give buyers a ready-to-sell option.</p><p>'+PH('Short summary of manufacturing capability and projects to date.')+'</p></div></div></section>';
  [['liners','Shower liners','crate','Water-resistant liners for bath and hotel use.'],['bags','Bags and films','tray','Carrier bags, produce bags and mailers.'],['cutlery','Cutlery','pellets','Forks, knives and spoons for food service.']].forEach(function(x,i){
    h+='<section class="sec '+(i%2?'':'sec--mist')+'" id="'+x[0]+'"><div class="wrap split split--center"><img src="img/'+x[2]+'.jpg" alt=""><div><span class="eyebrow">Product</span><h2 style="font-size:clamp(28px,3cqi,38px);color:var(--deep);margin-top:10px">'+x[1]+'</h2><p style="color:var(--muted);margin-top:14px">'+x[3]+' '+PH('Specs, sizes, pack counts')+'</p><div class="btns"><a class="btn btn--primary">Buy in bulk</a><a class="btn btn--outline">Buy retail</a><a class="arrow" data-go="oem" style="align-self:center">OEM partnership</a></div></div></div></section>';
  });
  return h;
}};
P.company={t:'Company',url:'company',sec:'company',r:function(){
  var h=hero({crumbs:[['Home','home'],['Company']],eyebrow:'Company',title:'About Ecoshell',sub:'We turn one of the world\'s largest unused food-waste streams into materials that put less plastic into everyday products.',img:'hero'});
  h+='<section class="sec"><div class="wrap split"><div><span class="eyebrow">About</span><h2 style="font-size:clamp(28px,3cqi,38px);color:var(--deep);margin-top:10px">Our story</h2><hr class="rule"></div><div class="prose"><p class="lead">Ecoshell started with a simple observation: eggshells are one of the largest unused waste streams in the world.</p><p>We found a way to turn that waste into a material that is economical, meets recycling goals, and works as a drop-in for manufacturers. Today we work with converters, brands and manufacturing partners across '+PH('markets')+'.</p></div></div></section>';
  h+='<section class="sec sec--mist" id="capabilities"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">Capabilities</span><h2>What we bring</h2></div></div><div class="grid g4">'+[['material','Material science','Eggshell processing and compounding know-how'],['manufacturing','Manufacturing','Partner network for moulding and assembly'],['doc','Testing and data','Pilot, test and reporting support'],['packaging','Supply','Eggshell sourcing and supply chain']].map(function(c){return '<div class="card">'+I(c[0])+'<h3>'+c[1]+'</h3><p>'+c[2]+'</p></div>'}).join('')+'</div></div></section>';
  h+='<section class="sec" id="news"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">News</span><h2>Latest from Ecoshell</h2></div><a class="arrow">All news</a></div><div class="grid g3">'+[['crate','Partnership','Ecoshell joins the PREVENT Waste Alliance'],['pellets','Product','[Product launch headline]'],['process','Event','[Event or award headline]']].map(function(x){return '<a class="card card--img"><img src="img/'+x[0]+'.jpg" alt=""><div class="body"><span class="tag">'+x[1]+'</span><h3>'+x[2]+'</h3><p style="font-size:14px;color:var(--stone)">[Date]</p></div></a>'}).join('')+'</div></div></section>';
  h+='<section class="sec sec--egg"><div class="wrap grid g3">'+[['team','Team','Meet the people behind Ecoshell.'],['collab','Collaboration','Example projects and how to work with us.'],['jobs','Job opportunities','Open roles and how to apply.']].map(function(c){return '<a class="card" data-go="'+c[0]+'"><h3>'+c[1]+'</h3><p>'+c[2]+'</p><span class="arrow">Go to '+c[1].toLowerCase()+'</span></a>'}).join('')+'</div></section>';
  return h;
}};
P.team={t:'Team',url:'company/team',sec:'company',parent:'company',r:function(){
  var h=hero({crumbs:[['Home','home'],['Company','company'],['Team']],eyebrow:'Team',title:'The people behind Ecoshell',sub:'A small team combining materials, operations and commercial experience.',img:'process'});
  h+='<section class="sec"><div class="wrap grid g3" style="gap:32px">'+[['andrew-bliss','Andrew Bliss','Founder & CEO'],['kyle-newell','Kyle Newell','Chief Commercial Officer'],['doug-hardesty','Doug Hardesty','Chief Operations Officer']].map(function(x){return '<div class="person"><img src="img/'+x[0]+'.jpg" alt="'+x[1]+'"><span class="role">'+x[2]+'</span><h3>'+x[1]+'</h3><p>'+PH('Two-line bio')+'</p><div style="display:flex;gap:16px"><a class="arrow">LinkedIn</a></div></div>'}).join('')+'</div></section>';
  return h;
}};
P.collab={t:'Collaboration',url:'company/collaboration',sec:'company',parent:'company',r:function(){
  var h=hero({crumbs:[['Home','home'],['Company','company'],['Collaboration']],eyebrow:'Collaboration',title:'Work with us',sub:'We co-develop with converters, brands, researchers and distributors who want a position in plastic reduction.',img:'tray'});
  h+='<section class="sec"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">Example projects</span><h2>Collaborations</h2></div><p>Partner names appear with permission.'+F('Permission')+'</p></div><div class="grid g3">'+[['crate','Converter','Pilot of Core in returnable crates'],['tray','Brand','Lower-plastic cosmetic jar'],['pellets','Research','Characterising bio calcium in HDPE']].map(function(x){return '<div class="card card--img"><img src="img/'+x[0]+'.jpg" alt=""><div class="body"><span class="tag">'+x[1]+'</span><h3>'+x[2]+'</h3><p>'+PH('Outcome')+'</p></div></div>'}).join('')+'</div></div></section>';
  h+='<section class="sec sec--mist"><div class="wrap gate"><div>'+form('Collaboration inquiry',['<div class="row">'+sel('Partner type',['Converter','Brand','Distributor','Research','Investor','Other'])+sel('Interest',['Co-development','Distribution','Pilot','Other'])+'</div>'])+'</div><div class="side"><div class="note-box">Tell us what you want to build. We reply within '+PH('X')+' business days.</div></div></div></section>';
  return h;
}};
P.jobs={t:'Job opportunities',url:'company/careers',sec:'company',parent:'company',r:function(){
  var h=hero({crumbs:[['Home','home'],['Company','company'],['Job opportunities']],eyebrow:'Careers',title:'Join Ecoshell',sub:'Help turn food waste into better materials.',img:'hero'});
  h+='<section class="sec"><div class="wrap"><div class="sec-head"><div><span class="eyebrow">Open roles</span><h2>Current openings</h2></div></div><dl class="list">'+[['Commercial','[Role title] · [Location] · [Full-time]'],['Operations','[Role title] · [Location] · [Full-time]'],['Technical','[Role title] · [Location] · [Contract]']].map(function(r){return '<div><dt>'+r[0]+'</dt><dd style="display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap"><span class="ph">'+r[1]+'</span><a class="arrow">View role</a></dd></div>'}).join('')+'</dl><p style="margin-top:24px;color:var(--muted)">No role that fits? Send your CV to '+PH('careers@ecoshell.eco')+'.</p></div></section>';
  return h;
}};
P.responsibility={t:'Corporate responsibility',url:'company/responsibility',sec:'company',parent:'company',r:function(){
  var h=hero({crumbs:[['Home','home'],['Company','company'],['Corporate responsibility']],eyebrow:'Corporate responsibility',title:'How we run the company',sub:'Responsible sourcing, honest claims and a safe workplace.',img:'process',deep:true});
  h+='<section class="sec"><div class="wrap grid g3">'+[['Responsible sourcing','How we source eggshell and choose partners.'],['Honest claims','Every claim tied to test data, aligned with the FTC Green Guides.'],['People and safety','Workplace safety and fair employment.']].map(function(c){return '<div class="card"><h3>'+c[0]+'</h3><p>'+c[1]+' '+PH('Detail')+'</p></div>'}).join('')+'</div></section>';
  return h;
}};
P.contact={t:'Contact',url:'contact',sec:'contact',r:function(){
  var h=hero({crumbs:[['Home','home'],['Contact']],eyebrow:'Contact',title:'Talk to Ecoshell',sub:'Choose the type of inquiry so it reaches the right person.',img:'pellets'});
  h+='<section class="sec"><div class="wrap gate"><div><div class="seg" id="ctype" role="group" aria-label="Inquiry type">'+['General','Sales','Co-development','Press'].map(function(t){return '<button type="button" aria-pressed="false" data-type="'+t+'">'+t+'</button>'}).join('')+'</div><div style="margin-top:18px" id="cform">'+form('<span id="ctitle">General inquiry</span>',['<div class="row">'+sel('Role',['Procurement','Sustainability','Engineering','Marketing','Press','Other'])+sel('Polymer (if relevant)',['Not sure','PP','HDPE','Other'])+'</div>'],'Send')+'</div></div><div class="side"><span class="eyebrow">Direct contacts</span><dl class="list"><div><dt>General</dt><dd class="ph">[info@ecoshell.eco]</dd></div><div><dt>Sales</dt><dd class="ph">[sales@ecoshell.eco]</dd></div><div><dt>Co-development</dt><dd class="ph">[partners@ecoshell.eco]</dd></div><div><dt>Press</dt><dd class="ph">[press@ecoshell.eco]</dd></div></dl></div></div></section>';
  return h;
}};
P.resources={t:'Insights & Resources',url:'resources',sec:'resources',r:function(){
  var h=hero({crumbs:[['Home','home'],['Insights & Resources']],eyebrow:'Insights & Resources',title:'Insights &amp; resources',sub:'Articles, technical downloads, position papers and product lists, plus custom one-pagers for your internal teams.',img:'tray'});
  var dl=function(t,s){return '<a class="dl"><i>PDF</i><div><b>'+t+'</b><small>'+s+'</small></div></a>'};
  h+='<section class="sec"><div class="wrap grid g3" style="gap:32px"><div class="side"><span class="eyebrow">Tech downloads</span>'+dl('TDS · Core','Technical data sheet')+dl('SDS · Core','Safety data sheet')+dl('Processing guide','All Core grades')+'</div><div class="side"><span class="eyebrow">Position papers</span>'+dl('Ecoshell vs. bioplastics','Why the recycling stream matters')+dl('Bio calcium vs. limestone','Material and LCA comparison')+dl('Meeting EPR with material reduction','Briefing note')+'</div><div class="side"><span class="eyebrow">Product lists</span>'+dl('Full product list','All platforms and grades')+dl('Ecoshell products catalogue','Liners, bags, cutlery')+'</div></div></section>';
  h+='<section class="sec sec--deep on-dark" id="onepager"><div class="wrap gate"><div><span class="eyebrow">For sustainability and procurement teams</span><h2 style="font-size:clamp(28px,3cqi,40px);margin-top:10px">Get a custom one-pager for your internal case</h2><p style="margin-top:16px;max-width:50ch">Tell us your company and role. We will send a one-page summary of Ecoshell tailored to your products and targets, ready to share with your colleagues.</p><dl class="list" style="margin-top:26px"><div><dt>Sustainability</dt><dd>Reduction, LCA and reporting summary</dd></div><div><dt>Procurement</dt><dd>Supply, pricing basis and qualification path</dd></div><div><dt>Engineering</dt><dd>Processing and performance summary</dd></div></dl></div><div style="color:var(--ink)">'+form('Request marketing materials',[sel('Your role',['Sustainability manager','Procurement lead','Engineering','Marketing','Other']),sel('Material needed',['Custom one-pager','Sustainability summary','Procurement summary'])],'Request by email')+'<p style="font-size:14px;color:var(--on-dark);margin-top:10px">A work email is required. Materials are sent by email, not downloaded.</p></div></div></section>';
  return h;
}};

